name: napapiri
favicon: null
layout_spectrum: 0.24384979926981032
typography_spectrum: 0.742090466665104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.10840041283518076
  lightness: 0.9715607350226492
  saturation: 0.3025659976992756
  rhythmicContrast: 0.7902454589493573
purpose: []
