typography_spectrum: 0.90785
color:
  brandColors:
    - '#eaeae8'
    - '#94a4bd'
    - '#16211c'
    - '#63391e'
    - '#a8612d'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.48777
analytics:
  google: null
  facebook: null
  twitter: null
name: napapiri
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: we do ice
purpose: []
