name: napapiri
favicon: null
layout_spectrum: 0.51151
typography_spectrum: 0.90785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaeae8'
    - '#94a4bd'
    - '#16211c'
    - '#63391e'
    - '#a8612d'
  brandStrength: 0.10840041283518076
  lightness: 0.9715607350226492
  saturation: 0.3025659976992756
  rhythmicContrast: 0.75
purpose: []
